---
- name: Deploy Scientific Calculator
  hosts: localhost
  remote_user: nitish
  become: false
  tasks:

    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "nitish757/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
      
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run the Calculator Container
      command: docker run -it -d --name calculator nitish757/calculator
